[package]
name = "pixluna-rslib"
edition = "2024"
description = "Extra library for pixluna written in Rust"
license = "MPL-2.0"
homepage = "https://github.com/PixLunaLab/pixluna"
repository = "https://github.com/PixLunaLab/pixluna"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.25.8"
js-sys = "0.3.81"
mimetype-detector = "0.2.2"
wasm-bindgen = "0.2.104"

