[package]
name = "pixluna-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.25.8"
js-sys = "0.3.81"
mimetype-detector = "0.2.2"
wasm-bindgen = "0.2.104"

